version: 1.0.0-{branch}{build}
os: Visual Studio 2015 RC
branches:
  only:
  - develop
configuration: Release
before_build:
- ps: >-
    $nugetExe = [IO.Path]::Combine((Get-Location).Path, "nuget.exe")

    (new-object Net.WebClient).DownloadFile("http://www.nuget.org/nuget.exe", $nugetExe)   
    
    . $nugetExe restore MSTest.VSHost.sln
build:
  parallel: true
  verbosity: minimal
test:
  assemblies: '**\*.tests.dll'