version: 1.0.0-{branch}{build}
os: Visual Studio 2015 RC
environment:
  VisualStudioVersion: 14.0
branches:
  only:
  - develop
configuration: Release
before_build:
- nuget restore
build:
  parallel: false
  verbosity: detailed
test:
  assemblies: '**\*.tests.dll'